language: php

php:
  - 5.3
  - 5.4

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

branches:
  only:
    master

notifications:
  email:
    - kotlyar.maksim@gmail.com
    - brainreflex@gmail.com